SCRUM-153-Update-CI-Excempt-Stop-On-Failure

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -40,7 +40,7 @@ jobs:
         run: npm run test || true # Allow unit test failures without failing
 
       - name: Run Coverage Tests
-        run: npm run test:coverage
+        run: npm run test:coverage || true # Allow coverage test failures without failing
 
       - name: Upload Coverage Report
         uses: actions/upload-artifact@v4
